definitions:
  # where your page definitions are hosted ('local', 'remote' or 'ensemble')
  from: ensemble

  # for embedding definitions locally in your Flutter App
  local:
    path: assets/ensemble/pages/

  # for hosting definitions on your own server
  remote:
    path: https://ensemble-s3.s3.us-west-1.amazonaws.com/ensemble/definitions/

  # for Ensemble-hosted definitions, simply enter your Ensemble's app key
  ensemble:
    appKey: <your_ensemble_app_key>
