definitions:
  # where your page definitions are hosted ('local', 'remote' or 'ensemble')
  from: ensemble

  i18n:
    #locale string e.g. en, nl etc. If empty, user's device locale is used
    defaultLocale: nl
    #if strings in defaultLocale are not found, which locale to use instead
    fallbackLocale: en
    #use country code after locale code such as en_us
    useCountryCode: false

  # for embedding definitions locally in your Flutter App
  local:
    # the root directory where all your Apps definitions reside
    path: ensemble/apps/
    # appId represents an App, and is a folder under the root directory
    # Note that each App directory also has to be added manually under pubspec.yaml
    appId: helloApp
    # appHome is the name of the home screen. This will be the first screen when your App loads
    appHome: Hello Home
    #folder that contains the translated strings for all locales
    i18nPath: ensemble/i18n

  # for hosting definitions on your own server
  remote:
    path: <your_http_server_hosting_the_definitions>
    appId: helloApp
    appHome: Hello Home
    i18nPath: <full_url_including_scheme_and_host_to_i18n_directory_on_your_server>

  # for Ensemble-hosted definitions, simply enter your Ensemble's app key
  ensemble:
    # this is the Ensemble server URL. Do not change
    path: https://pz0mwfkp5m.execute-api.us-east-1.amazonaws.com/dev
    # appId can be found on Ensemble Studio.
    # mastercard appId: e74abf50-6177-456f-8556-0f01e5235860
    # kitchen appId: e24402cb-75e2-404c-866c-29e6c3dd7992
    #kpn
    appId: 40dcdbe9-1ac3-4aab-8ee2-0bcdd2f1ca7b
    #appId: 40dcdbe9-1ac3-4aab-8ee2-0bcdd2f1ca7b
    i18nPath: https://raw.githubusercontent.com/EnsembleUI/ensemble_starter/main/ensemble/i18n
    enableCache: true
    # i18nPath: https://d1x5t4jfwtkdjl.cloudfront.net/web/assets/assets/i18n